name: "prometheus2"
arch: "arm64"
platform: "linux"
version: "v2.54.0"
version_schema: semver
description: The Prometheus monitoring system and time series database.
maintainer: Ruohang Feng <rh@vonng.com>
vendor: "Prometheus"
homepage: "https://github.com/prometheus/prometheus"
license: "Apache-2.0 license"


contents:

  # 2 binary files
  - src: prometheus/prometheus
    dst: /usr/bin/prometheus
    file_info:
      mode: 0755

  - src: prometheus/promtool
    dst: /usr/bin/promtool
    file_info:
      mode: 0755

  # config directory
  - dst: /etc/prometheus/
    type: dir
    file_info:
      mode: 0700
      owner: prometheus
      group: prometheus


  # 3 Config files
  - src: prometheus/prometheus.yml
    dst: /etc/prometheus/prometheus.yml
    type: config|noreplace
    file_info:
      mode: 0700
      owner: prometheus
      group: prometheus

  - src: src/default
    dst: /etc/default/prometheus
    type: config|noreplace
    file_info:
      mode: 0700
      owner: prometheus
      group: prometheus

  - src: src/service
    dst: /usr/lib/systemd/system/prometheus.service
    type: config|noreplace


  # 2 console libraries
  - src: prometheus/consoles
    dst: /usr/share/prometheus/consoles
    type: tree

  - src: prometheus/console_libraries
    dst: /usr/share/prometheus/console_libraries
    type: tree


scripts:
  preinstall: src/preinstall.sh
  postinstall: src/postinstall.sh
  preremove: src/preremove.sh
  # postremove:  src/postremove.sh
